--- Makefile.orig	2009-11-17 16:13:19.000000000 -0500
+++ Makefile	2009-11-17 16:16:25.000000000 -0500
@@ -16,18 +16,7 @@
            aclocal.m4 configure configure.ac install-sh Makefile.in \
            bits lisp misc tex texinfo utils
 
-all: Makefile bbdb info    gnus
-
-Makefile:: Makefile.in
-	./config.status
-
-Makefile:: configure
-	@echo "Configure has changed, you may need to rerun configure!"
-	exit 1
-
-configure: configure.ac
-	@echo "configure.ac has changed. Please rerun autoconf!"
-	exit 1
+all: bbdb info    gnus
 
 bbdb:
 	cd lisp; $(MAKE) bbdb
