.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BBDB-CID.PL 1 "March 31, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
bbdb-cid \- Caller-ID-logger
.SH SYNOPSIS
.B bbdb-cid
.SH DESCRIPTION
Opens the modem and waits for it to print caller-ID data.  When it does,
it logs it to a file, parses it, and pops up a window using "xmessage".
If the number is present in your .bbdb file, it shows the name (or company)
associated with it.  

.IR "You have to edit the Skript and change it to fit into your System!"

This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.SH SEE ALSO
.BR bbdb-areacode-split (1),
.BR bbdb-unlazy-lock (1).
.BR bbdb-srv (1).
.br
The bbdb is fully documented by
.IR "The insidious Big Brother Database for mail and news" ,
available via the Infonode
.BR bbdb
.
.SH AUTHOR
This manual page was written by Joerg Jaspert (JJ) <joerg@goliathbbs.dnsalias.net>,
for the Debian GNU/Linux system (but may be used by others).
